variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  APT_PKGS: "libudunits2-dev libgdal-dev libgeos-dev libproj-dev libcurl4-openssl-dev libssh2-1-dev libssl-dev libxml2-dev zlib1g-dev git"

before_script:
  - wget --no-check-certificate -O /usr/local/share/ca-certificates/DOIRootCA2.crt https://raw.githubusercontent.com/dblodgett-usgs/hydrogeoenv/master/linux/DOIRootCA2.cer
  - chmod 644 /usr/local/share/ca-certificates/DOIRootCA2.crt && update-ca-certificates
  - apt-get update
  - apt-get install -y --no-install-recommends ${APT_PKGS}
  - apt-get install -y --no-install-recommends qpdf pandoc pandoc-citeproc
  - export PATH="/usr/local/lib/R/site-library/littler/examples/:${PATH}"
  - echo "options(Ncpus = $(nproc --all))" >> /usr/local/lib/R/etc/Rprofile.site
  - install2.r devtools
  - r -e 'devtools::install_dev_deps()'

test:
  stage: test
  tags:
    - chs-shared
  image: code.chs.usgs.gov:5001/wma/hydrogeoenv:rocker-geospatial
  script:
    - r -e 'devtools::check(check_dir = ".")'
    - r -e 'covr::report(file = "covr.html")'
  artifacts:
    paths:
      - "*.Rcheck"
      - "covr.html"
