library(testthat)
library("nhdplusTools")
library("sf")
library("dplyr")
timer <- Sys.time()
test_check("nhdplusTools", filter = "nhdplus")
print(Sys.time() - timer)
test_check("nhdplusTools", filter = "collapse")
print(Sys.time() - timer)
test_check("nhdplusTools", filter = "get")
print(Sys.time() - timer)
test_check("nhdplusTools", filter = "index")
print(Sys.time() - timer)
test_check("nhdplusTools", filter = "reconcile")
print(Sys.time() - timer)
test_check("nhdplusTools", filter = "refactor")
print(Sys.time() - timer)
test_check("nhdplusTools", filter = "subset")
print(Sys.time() - timer)
# test_check("nhdplusTools", filter = "split")
# print(Sys.time() - timer)
