#' Collapse Catchment Boundaries
#' @description Collapses catchments according to a set of outlet catchments.
#' @param fline_rec sf data.frame Reconciled flowlines as generated by `refactor_nhdplus`
#' @param cat_rec sf data.frame Reconciled catchments as genberated by `reconcile_catchments`
#' @param outlets data.frame with "ID" and "type" columns. "ID" must be identifiers from
#' fline and cat data.frames. "type" should be "outlet", or "terminal".
#' "outlet" will include the specified ID.
#' "terminal" will be treated as a terminal node with nothing downstream.
#' This parameter may change.
#' @param flowline sf data.frame with original nhdplus network flowlines.
#' @details This function operates on the catchment network as a node-edge graph.
#' The outlet types are required to ensure that graph searches start from the
#' appropriate nodes and includes the appropriate catchments. Outlets such as gages
#' should be treated as "outlet" outlets.
#' While it may be possible for the algorithm to determine terminal outlets, at this
#' time, it is required that they be specified explicitely as "terminal" outlet types.
#'
#' The function checks supplied catchment outlets to make sure they connect to downstream
#' catchments. This requires the original NHDPlus Flowlines' levelpathID and HydroSequence
#' attributes. Checks verify that the outlet of the levelpath of each supplied outlet is
#' in the supplied outlet set. If the outlet of a levelpath is not in the supplied set, it
#' is added along with other catchments that contribute to the same receiving catchment.
#' These checks ensure that all output catchments have one and only one input and output
#' nexus and that all catchments are well-connected.
#'
#' Note that at this time, when a confluence has to be added to enforce network connectivity,
#' all tributaries to the confluence are added as catchments. This can lead to several
#' catchments being added to the output that may not be desired.
#'
#' @export
#' @importFrom igraph graph_from_data_frame topo_sort incident_edges V bfs head_of shortest_paths
#' @importFrom sf st_cast st_union st_geometry st_sfc st_sf st_crs st_set_geometry st_line_merge st_geometry_type
#' @importFrom dplyr filter mutate left_join select distinct case_when
#' @examples
#' source(system.file("extdata", "walker_data.R", package = "nhdplusTools"))
#' outlets <- data.frame(ID = c(31, 3, 5, 1, 45, 92),
#'                       type = c("outlet", "outlet", "outlet", "terminal", "outlet", "outlet"),
#'                       stringsAsFactors = FALSE)
#' aggregated <- aggregate_catchments(walker_fline_rec, walker_catchment_rec,
#'                                  outlets, walker_flowline)
#' plot(aggregated$cat_sets$geom, lwd = 3, border = "red")
#' plot(walker_catchment_rec$geom, lwd = 1.5, border = "green", col = NA, add = TRUE)
#' plot(walker_catchment$geom, lwd = 1, add = TRUE)
#' plot(walker_flowline$geom, lwd = .7, col = "blue", add = TRUE)
#'
#' plot(aggregated$cat_sets$geom, lwd = 3, border = "black")
#' plot(aggregated$fline_sets$geom, lwd = 3, col = "red", add = TRUE)
#' plot(walker_flowline$geom, lwd = .7, col = "blue", add = TRUE)
#'

aggregate_catchments <- function(fline_rec, cat_rec, outlets, flowline) {

  remove_flines <- filter(fline_rec, !ID %in% cat_rec$ID)
  if (any(remove_flines$ID %in% remove_flines$toID))
    stop("Found some flowlines without catchments that are
         not headwaters. This breaks critical assumptions.")
  # Actually remove superfluous flowlines.
  fline_rec <- filter(fline_rec, ID %in% cat_rec$ID)

  lps <- get_lps(fline_rec, flowline)

  outlets <- make_outlets_valid(outlets, fline_rec, lps) %>%
    distinct()

  outlets <- mutate(outlets, ID = paste0("cat-", ID))
  cat_rec <- mutate(cat_rec, ID = paste0("cat-", ID))

  # Build catchment and nexus data.frames to preserve sanity in graph traversal.
  catchment <- fline_rec %>%
    mutate(toID = ifelse(is.na(toID), 0, toID))

  # Join id to toID use ID as from nexus ID since we are assuming dendritic.
  nexus <- left_join(select(st_set_geometry(catchment, NULL), toID = ID),
                     select(st_set_geometry(catchment, NULL), fromID = ID, toID),
                     by = "toID") %>%
    mutate(nexID = paste0("nex-", toID),
           fromID = paste0("cat-", fromID),
           toID = paste0("cat-", toID)) %>%
    select(nexID, fromID, toID)

  # get fromID and toID straight with "nex-" prefix
  catchment <- mutate(st_set_geometry(catchment, NULL),
                      fromID = paste0("nex-", ID),
                      toID = paste0("nex-", toID),
                      ID = paste0("cat-", ID)) %>%
    select(fromID, toID, cat_ID = ID)

  # Convert the catchment network to a directed graph
  cat_graph <- graph_from_data_frame(d = catchment,
                                   directed = TRUE)

  outlets <- outlets %>%
    left_join(select(catchment, nexID_stem = fromID, ID = cat_ID), by = "ID") %>%
    left_join(select(catchment, nexID_terminal = toID, ID = cat_ID), by = "ID") %>%
    mutate(
      nexID = case_when(
        type == "outlet" ~ nexID_stem,
        type == "terminal" ~ nexID_terminal
      )
    ) %>%
    select(ID, type, nexID) %>%
    distinct()

  # sorted version of the graph to re-order outlets in upstream-downstream order.
  cat_graph_sort_verts <- topo_sort(cat_graph)
  outlet_verts <- cat_graph_sort_verts[names(cat_graph_sort_verts) %in% outlets$nexID]
  outlets <- outlets[match(names(outlet_verts), outlets$nexID), ]

  cat_sets <- data.frame(ID = outlets$nexID,
                         set = I(rep(list(list()), nrow(outlets))),
                         geom = I(rep(list(list()), nrow(outlets))),
                         stringsAsFactors = FALSE)

  fline_sets <- data.frame(ID = outlets$nexID,
                           set = I(rep(list(list()), nrow(outlets))),
                           geom = I(rep(list(list()), nrow(outlets))),
                           stringsAsFactors = FALSE)

  verts <- V(cat_graph)

  us_verts <- c()

  for (cat in seq_len(nrow(cat_sets))) {
    outlet <- filter(outlets, nexID == cat_sets$ID[cat])

    ut <- bfs(graph = cat_graph,
              root = cat_sets$ID[cat],
              neimode = "in",
              order = TRUE,
              unreachable = FALSE,
              restricted = verts)

    outlet_id <- as.integer(gsub("^cat-", "", outlets$ID[cat]))
    head_id <- lps$head_ID[which(lps$ID == outlet_id)]
    head_id <- head_id[head_id != outlet_id]

    if (length(head_id) == 0) head_id <- outlet_id # Then the outlet is a headwater.
    um <- find_um(us_verts, cat_graph,
                  cat_id = cat_sets$ID[cat],
                  head_id = head_id,
                  outlet_type = filter(outlets, nexID == cat_sets$ID[cat])$type)

    if (length(us_verts) > 0) {
      vert <- us_verts[which(um %in% us_verts)]

      if (length(vert) == 1) {
        # Since longest path is used in find_um if multiple paths are found
        # there is a chance that multiple us verts get consumed in a single step?
        us_verts <- us_verts[!us_verts %in% vert]
      }
    }

    um <- as.numeric(gsub("^nex-", "", um))

    fline_sets$geom[[cat]] <- filter(fline_rec, ID %in% um) %>%
      st_geometry() %>%
      st_cast("LINESTRING") %>%
      st_union()

    if (st_geometry_type(fline_sets$geom[[cat]]) == "MULTILINESTRING") {
      fline_sets$geom[[cat]] <- st_line_merge(fline_sets$geom[[cat]])
    }

    fline_sets$geom[[cat]] <- fline_sets$geom[[cat]][[1]]

    fline_sets$set[[cat]] <- um

    # Excludes the search node to avoid grabbing the downstream catchment.
    ut_verts <- ut$order[!is.na(ut$order) & names(ut$order) != cat_sets$ID[cat]]
    cat_sets$set[[cat]] <- filter(catchment, fromID %in% names(ut_verts))$cat_ID
    remove <- head_of(cat_graph, unlist(incident_edges(cat_graph, ut_verts, "in")))
    verts <- verts[!verts %in% remove]
    if (outlet$type == "outlet") {
      cat_sets$set[[cat]] <- c(cat_sets$set[[cat]], outlet$ID)
      verts <- verts[!names(verts) == outlet$nexID]
    }
    cat_sets$geom[[cat]] <- st_union(st_geometry(filter(cat_rec, ID %in% unlist(cat_sets$set[cat]))))[[1]]

    if (length(cat_sets$geom[[cat]]) == 0) browser()

    cat_sets$set[[cat]] <- as.numeric(gsub("^cat-", "", cat_sets$set[[cat]]))

    # us_verts are where we need to stop while stepping upstream.
    us_verts <- c(us_verts, cat_sets$ID[cat])
  }

  cat_sets$geom <- st_cast(st_sfc(cat_sets$geom, crs = st_crs(cat_rec)), "MULTIPOLYGON")
  cat_sets <- st_sf(cat_sets)
  cat_sets$ID <- as.numeric(gsub("^cat-", "", outlets$ID))

  fline_sets$geom <- st_sfc(fline_sets$geom, crs = st_crs(fline_rec))
  fline_sets <- st_sf(fline_sets)
  fline_sets$ID <- as.numeric(gsub("^cat-", "", outlets$ID))

  return(list(cat_sets = cat_sets, fline_sets = fline_sets))
}

get_lps <- function(fline_rec, flowline) {

  mapper <- member_mapper(st_set_geometry(fline_rec, NULL)) %>%
    mutate(orig_COMID = as.integer(floor(as.numeric(member_COMID)))) %>%
    left_join(select(st_set_geometry(flowline, NULL),
                     COMID, LevelPathID = LevelPathI, Hydroseq),
              by = c("orig_COMID" = "COMID")) %>%
    group_by(ID) %>%
    filter(LevelPathID == max(LevelPathID)) %>% # This could be problematic...
    ungroup() %>% group_by(LevelPathID)

  headwaters <- filter(mapper, Hydroseq == max(Hydroseq) &
                         (member_COMID == as.character(orig_COMID) |
                            member_COMID == as.character(orig_COMID + 0.1)))

  # First filter to get lowest catchment on level paths.
  # Second filter to get outlet ID of split catchments.
  outlets <- filter(mapper, Hydroseq == min(Hydroseq)) %>%
    group_by(orig_COMID) %>%
    filter(as.numeric(member_COMID) == max(as.numeric(member_COMID))) %>%
    ungroup()

  mapper %>%
    left_join(select(headwaters, head_ID = ID, LevelPathID),
              by = "LevelPathID") %>%
    left_join(select(outlets, tail_ID = ID, LevelPathID),
              by = "LevelPathID") %>%
    ungroup()
}

# Get the levelpath outlet IDs for each of the input outlets.
get_outlets <- function(outlets, lps) {
  distinct(left_join(outlets,
                     select(lps, ID, LevelPathID, tail_ID),
                     by = "ID"))
}

# Adds everything that contributes the same recieving catchment as a given tail id.
fix_nexus <- function(fline_rec, tail_ID) {
  add_ids <- filter(fline_rec,
                    toID == filter(fline_rec,
                                   ID == tail_ID)$toID)$ID
  data.frame(ID = add_ids,
             type = rep("outlet",
                        length(add_ids)),
             stringsAsFactors = FALSE)
}

fix_tail <- function(fline_rec, outlets, toID_tail_ID) {
  potential_add <- fix_nexus(fline_rec, toID_tail_ID)
  new <- !potential_add$ID %in% outlets$ID
  potential_add[new, ]
}

#' @description Given a set of outlets, works downstream adding outlets at the
#' outlet of each level path. This makes sure catchments get inserted so an upstream
#' catchment doesn't get orphaned in the middle of a larger catchment.
#' @param outlets the outlet list of gages, etc.
#' @param fline_rec the reconciled flowline network
#' @param lps level paths
#' @importFrom dplyr filter distinct select left_join group_by mutate
#' @noRd
make_outlets_valid <- function(outlets, fline_rec, lps) {

  otl <- get_outlets(outlets, lps)

  count_while <- 0
  while (!all(otl$tail_ID %in% otl$ID)) {

    bad <- which(!otl$tail_ID %in% otl$ID)

    for (add in seq_along(bad)) {
      bad_outlet <- otl[bad[add], ]

      outlets <- rbind(outlets,
                       fix_nexus(fline_rec, bad_outlet$tail_ID))
    }
    otl <- get_outlets(outlets, lps)

    count_while <- count_while + 1
    if (count_while > 1000) stop("Stuck in a while loop trying to fix disconnected outlets.")
  }

  otl_2 <- otl %>%
    # Need to check that a "next down tributary" in the outlet set has a break along the
    # main stem that each outlet contributes to.
    left_join(select(st_set_geometry(fline_rec, NULL), ID, toID), by = "ID") %>%
    left_join(select(lps, ID, toID_hydroseq = Hydroseq,
                     toID_tail_ID = tail_ID, toID_LevelpathID = LevelPathID),
              by = c("toID" = "ID")) %>%
    # this grabs the most downstream if duplicates were generated.
    group_by(ID) %>% filter(toID_hydroseq == min(toID_hydroseq)) %>% ungroup() %>%
    # This eliminates groups where only one thing goes to a given tail_ID.
    group_by(toID_tail_ID) %>% filter(n() > 1) %>% ungroup() %>%
    # This grabs all the inflows to the nexus that each of these outlets is at.
    left_join(select(st_set_geometry(fline_rec, NULL), toID_fromID = ID, toID), by = "toID") %>%
    mutate(type = "add_outlet") %>%
    select(ID = toID_fromID, type, LevelPathID = toID_LevelpathID, tail_ID) %>%
    distinct()

    # Need to verify that all ID == tail_ID instances are connected.
    # They might have been missed above.

  if (any(grepl("add_outlet", otl_2$type))) {
    otl_2$type <- "outlet"
    outlets <- distinct(rbind(outlets, otl_2[, c("ID", "type")]))
  }

  otl <- get_outlets(outlets, lps)
  tail_outlets <- which(otl$ID == otl$tail_ID & otl$type != "terminal")

  for (check in seq_along(tail_outlets)) {
    outlets <- rbind(outlets,
                     fix_tail(fline_rec, outlets, otl$ID[check]))

    connected <- FALSE
    while (!connected) {
      toID <- filter(fline_rec, ID == otl$ID[check])$toID
      toID_tail_ID <- filter(lps, ID == toID)$tail_ID

      if (!all(toID_tail_ID %in% otl$tail_ID)) {
        outlets <- rbind(outlets,
                         fix_tail(fline_rec, outlets, unique(toID_tail_ID)))
      } else {
        connected <- TRUE
      }
      otl <- get_outlets(outlets, lps)
    }
  }

  return(outlets)
}

#' @description Finds upstream nearest upstream main stem shortest path to
#' either the list of verticies that might be upstream or the up main headwater.
#' @param us_verts upstream verticies that should be used as stop points.
#' @param cat_graph the catchment network to be searched.
#' @param cat_id the catchment identifier to start at.
#' @param head_id the upstream mainstem top catchment identifier.
#' @param outlet_type the type of outlet chosen from "outlet", or "terminal".
#' @noRd
find_um <- function(us_verts, cat_graph, cat_id, head_id, outlet_type) {
  um <- c()

  if (length(us_verts) > 0) {
    suppressWarnings(paths <- shortest_paths(cat_graph,
                            from = cat_id,
                            to = us_verts,
                            mode = "in"))

    if (length(paths$vpath) > 1) {
      path_lengths <- lengths(sapply(paths$vpath, names))
    } else {
      path_lengths <- length(names(paths$vpath[[1]]))
    }

    if (any(path_lengths > 0)) {
      path_lengths[path_lengths == 0] <- NA
      um <- names(paths$vpath[which(path_lengths == min(path_lengths, na.rm = TRUE))][[1]])
      um <- um[!um %in% us_verts] # Path includes the "to" but don't want to include it!
    }
  }

  # then look for headwater.
  if (length(um) == 0) {
    um <- names(shortest_paths(cat_graph,
                               from = cat_id,
                               to = paste0("nex-", head_id),
                               mode = "in")$vpath[[1]])
  }

  return(um)
}
